import { Product, Recipe, Testimonial } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Chocalhos',
    description: 'Produzido com linha 100% algodão, enchimento anti-alérgico, olhinhos com trava de segurança e guizo (que emite som suave)',
    images: [
      '/bebe/chocalho-ursinho-aviador.webp',
      '/bebe/chocalho-cachorro.webp',
      '/bebe/chocalho-girafa.webp',
      '/bebe/chocalho-leao.webp',
      '/bebe/chocalho-abelha.webp',
      '/bebe/chocalho-raposa.webp',
      '/bebe/chocalho-hipo.webp'
    ],
    category: 'Bebê',
  },
  {
    id: '2',
    name: 'Manta para Bebê',
    description: 'Manta delicada e quentinha para os primeiros dias do seu bebê.',
    image: 'https://images.pexels.com/photos/6899790/pexels-photo-6899790.jpeg',
    category: 'Bebê',
  },
  {
    id: '3',
    name: 'Conjunto de Casaquinho e Sapatinho',
    description: 'Conjunto completo para manter seu bebê quentinho e elegante.',
    image: 'https://images.pexels.com/photos/5797999/pexels-photo-5797999.jpeg',
    category: 'Bebê',
  },
  {
    id: '4',
    name: 'Mobile de Bichinhos',
    description: 'Mobile colorido com bichinhos de crochê para entreter o bebê.',
    image: 'https://images.pexels.com/photos/3933457/pexels-photo-3933457.jpeg',
    category: 'Bebê',
  },
  {
    id: '5',
    name: 'Boneca de Crochê',
    description: 'Boneca de crochê segura e macia para as crianças brincarem.',
    image: 'https://images.pexels.com/photos/3933460/pexels-photo-3933460.jpeg',
    category: 'Criança',
  },
  {
    id: '6',
    name: 'Urso de Pelúcia em Crochê',
    description: 'Ursinho fofo e seguro para as crianças de todas as idades.',
    image: 'https://images.pexels.com/photos/4553016/pexels-photo-4553016.jpeg',
    category: 'Criança',
  },
  {
    id: '7',
    name: 'Touca Infantil',
    description: 'Touca quentinha e confortável para dias mais frios.',
    image: 'https://images.pexels.com/photos/5797991/pexels-photo-5797991.jpeg',
    category: 'Criança',
  },
  {
    id: '8',
    name: 'Conjunto Cachecol e Luvas',
    description: 'Conjunto completo para proteger as crianças do frio.',
    image: 'https://images.pexels.com/photos/5797908/pexels-photo-5797908.jpeg',
    category: 'Criança',
  },
  {
    id: '9',
    name: 'Capa de Almofada',
    description: 'Capas de almofada decorativas para sala e quarto.',
    image: 'https://images.pexels.com/photos/6707629/pexels-photo-6707629.jpeg',
    category: 'Decoração',
  },
  {
    id: '10',
    name: 'Centro de Mesa',
    description: 'Centro de mesa elegante para decorar sua sala de jantar.',
    image: 'https://images.pexels.com/photos/6707632/pexels-photo-6707632.jpeg',
    category: 'Decoração',
  },
  {
    id: '11',
    name: 'Porta-copos',
    description: 'Conjunto de porta-copos decorativos e funcionais.',
    image: 'https://images.pexels.com/photos/6069552/pexels-photo-6069552.jpeg',
    category: 'Decoração',
  },
  {
    id: '12',
    name: 'Guirlanda',
    description: 'Guirlanda decorativa para porta de entrada.',
    image: 'https://images.pexels.com/photos/6758797/pexels-photo-6758797.jpeg',
    category: 'Decoração',
  },
  {
    id: '13',
    name: 'Cachecol',
    description: 'Cachecol quentinho e elegante para presente.',
    image: 'https://images.pexels.com/photos/8489669/pexels-photo-8489669.jpeg',
    category: 'Presentes',
  },
  {
    id: '14',
    name: 'Bolsa de Mão',
    description: 'Bolsa de mão feita em crochê, elegante e durável.',
    image: 'https://images.pexels.com/photos/7173046/pexels-photo-7173046.jpeg',
    category: 'Presentes',
  },
  {
    id: '15',
    name: 'Conjunto de Porta-trecos',
    description: 'Conjunto de cestas pequenas para organização.',
    image: 'https://images.pexels.com/photos/6707778/pexels-photo-6707778.jpeg',
    category: 'Presentes',
  },
  {
    id: '16',
    name: 'Conjunto de Xícara',
    description: 'Conjunto com xícara e capa decorativa em crochê.',
    image: 'https://images.pexels.com/photos/6707789/pexels-photo-6707789.jpeg',
    category: 'Presentes',
  },
  {
    id: '17',
    name: 'Decoração de Natal',
    description: 'Conjunto de enfeites para árvore de Natal.',
    image: 'https://images.pexels.com/photos/3303614/pexels-photo-3303614.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '18',
    name: 'Coração Decorativo',
    description: 'Coração decorativo para Dia dos Namorados.',
    image: 'https://images.pexels.com/photos/6957769/pexels-photo-6957769.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '19',
    name: 'Cestinha de Páscoa',
    description: 'Cestinha decorada para Páscoa.',
    image: 'https://images.pexels.com/photos/6957886/pexels-photo-6957886.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '20',
    name: 'Decoração de Halloween',
    description: 'Conjunto de decorações temáticas para Halloween.',
    image: 'https://images.pexels.com/photos/6648276/pexels-photo-6648276.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '21',
    name: 'Amigurumi Personalizado',
    description: 'Amigurumi feito sob medida conforme pedido do cliente.',
    image: 'https://images.pexels.com/photos/6683350/pexels-photo-6683350.jpeg',
    category: 'Personalizados',
  },
  {
    id: '22',
    name: 'Toalha com Monograma',
    description: 'Toalha com iniciais ou nome bordado em crochê.',
    image: 'https://images.pexels.com/photos/6474573/pexels-photo-6474573.jpeg',
    category: 'Personalizados',
  },
  {
    id: '23',
    name: 'Chaveiro Personalizado',
    description: 'Chaveiro de crochê personalizado com nome ou formato.',
    image: 'https://images.pexels.com/photos/6957904/pexels-photo-6957904.jpeg',
    category: 'Personalizados',
  },
  {
    id: '24',
    name: 'Conjunto para Bebê Personalizado',
    description: 'Conjunto personalizado com nome e cores à escolha.',
    image: 'https://images.pexels.com/photos/7180295/pexels-photo-7180295.jpeg',
    category: 'Personalizados',
  },
];

// ... recipes e testimonials igual ao seu

