import { Product, Recipe, Testimonial } from '@/lib/types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Chocalhos',
    description: 'Produzidos com linha 100% algodão, enchimento anti-alérgico, olhinhos com trava de segurança e guizo.',
    images: [
      'bebe/chocalho-ursinho-aviador.webp',
      'bebe/chocalho-cachorro.webp',
      'bebe/chocalho-girafa.webp',
      'bebe/chocalho-leao.webp',
      'bebe/chocalho-abelha.webp',
      'bebe/chocalho-raposa.webp',
      'bebe/chocalho-hipo.webp'
    ],
    category: 'Bebê',
  },
  {
    id: '2',
    name: 'Porta Maternidade',
    description: 'Personalize o primeiro cantinho do seu bebê com um porta maternidade exclusivo feito à mão.',
    images: [
      'bebe/porta-maternidade1.webp',
      'bebe/porta-maternidade2.webp',
      'bebe/porta-maternidade3.webp'
    ],
    category: 'Bebê',
  },
  {
    id: '3',
    name: 'Faixinha de Cabelo',
    description: 'Um toque de charme e delicadeza para o visual das pequenas.',
    images: [
      'bebe/faixinha-cabeca1.webp',
      'bebe/faixinha-cabeca2.webp',
      'bebe/faixinha-cabeca3.webp',
      'bebe/faixinha-cabeca4.webp',
      'bebe/faixinha-cabeca5.webp',
      'bebe/faixinha-cabeca6.webp'
    ],
    category: 'Bebê',
  },
  {
    id: '4',
    name: 'Kit Higiene',
    description: 'Nosso kit higiene em crochê artesanal é perfeito para guardar itens essenciais com muito cuidado e estilo.',
    image: 'bebe/kit-higiene.webp',
    category: 'Bebê',
  },
  {
    id: '5',
    name: 'Boneca de Crochê',
    description: 'Boneca de crochê segura e macia para as crianças brincarem.',
    image: 'https://images.pexels.com/photos/3933460/pexels-photo-3933460.jpeg',
    category: 'Criança',
  },
  {
    id: '6',
    name: 'Urso de Pelúcia em Crochê',
    description: 'Ursinho fofo e seguro para as crianças de todas as idades.',
    image: 'https://images.pexels.com/photos/4553016/pexels-photo-4553016.jpeg',
    category: 'Criança',
  },
  {
    id: '7',
    name: 'Touca Infantil',
    description: 'Touca quentinha e confortável para dias mais frios.',
    image: 'https://images.pexels.com/photos/5797991/pexels-photo-5797991.jpeg',
    category: 'Criança',
  },
  {
    id: '8',
    name: 'Conjunto Cachecol e Luvas',
    description: 'Conjunto completo para proteger as crianças do frio.',
    image: 'https://images.pexels.com/photos/5797908/pexels-photo-5797908.jpeg',
    category: 'Criança',
  },
  {
    id: '9',
    name: 'Capa de Almofada',
    description: 'Capas de almofada decorativas para sala e quarto.',
    image: 'https://images.pexels.com/photos/6707629/pexels-photo-6707629.jpeg',
    category: 'Decoração',
  },
  {
    id: '10',
    name: 'Centro de Mesa',
    description: 'Centro de mesa elegante para decorar sua sala de jantar.',
    image: 'https://images.pexels.com/photos/6707632/pexels-photo-6707632.jpeg',
    category: 'Decoração',
  },
  {
    id: '11',
    name: 'Porta-copos',
    description: 'Conjunto de porta-copos decorativos e funcionais.',
    image: 'https://images.pexels.com/photos/6069552/pexels-photo-6069552.jpeg',
    category: 'Decoração',
  },
  {
    id: '12',
    name: 'Guirlanda',
    description: 'Guirlanda decorativa para porta de entrada.',
    image: 'https://images.pexels.com/photos/6758797/pexels-photo-6758797.jpeg',
    category: 'Decoração',
  },
  {
    id: '13',
    name: 'Cachecol',
    description: 'Cachecol quentinho e elegante para presente.',
    image: 'https://images.pexels.com/photos/8489669/pexels-photo-8489669.jpeg',
    category: 'Presentes',
  },
  {
    id: '14',
    name: 'Bolsa de Mão',
    description: 'Bolsa de mão feita em crochê, elegante e durável.',
    image: 'https://images.pexels.com/photos/7173046/pexels-photo-7173046.jpeg',
    category: 'Presentes',
  },
  {
    id: '15',
    name: 'Conjunto de Porta-trecos',
    description: 'Conjunto de cestas pequenas para organização.',
    image: 'https://images.pexels.com/photos/6707778/pexels-photo-6707778.jpeg',
    category: 'Presentes',
  },
  {
    id: '16',
    name: 'Conjunto de Xícara',
    description: 'Conjunto com xícara e capa decorativa em crochê.',
    image: 'https://images.pexels.com/photos/6707789/pexels-photo-6707789.jpeg',
    category: 'Presentes',
  },
  {
    id: '17',
    name: 'Decoração de Natal',
    description: 'Conjunto de enfeites para árvore de Natal.',
    image: 'https://images.pexels.com/photos/3303614/pexels-photo-3303614.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '18',
    name: 'Coração Decorativo',
    description: 'Coração decorativo para Dia dos Namorados.',
    image: 'https://images.pexels.com/photos/6957769/pexels-photo-6957769.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '19',
    name: 'Cestinha de Páscoa',
    description: 'Cestinha decorada para Páscoa.',
    image: 'https://images.pexels.com/photos/6957886/pexels-photo-6957886.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '20',
    name: 'Decoração de Halloween',
    description: 'Conjunto de decorações temáticas para Halloween.',
    image: 'https://images.pexels.com/photos/6648276/pexels-photo-6648276.jpeg',
    category: 'Datas comemorativas',
  },
  {
    id: '21',
    name: 'Amigurumi Personalizado',
    description: 'Amigurumi feito sob medida conforme pedido do cliente.',
    image: 'https://images.pexels.com/photos/6683350/pexels-photo-6683350.jpeg',
    category: 'Personalizados',
  },
  {
    id: '22',
    name: 'Toalha com Monograma',
    description: 'Toalha com iniciais ou nome bordado em crochê.',
    image: 'https://images.pexels.com/photos/6474573/pexels-photo-6474573.jpeg',
    category: 'Personalizados',
  },
  {
    id: '23',
    name: 'Chaveiro Personalizado',
    description: 'Chaveiro de crochê personalizado com nome ou formato.',
    image: 'https://images.pexels.com/photos/6957904/pexels-photo-6957904.jpeg',
    category: 'Personalizados',
  },
  {
    id: '24',
    name: 'Conjunto para Bebê Personalizado',
    description: 'Conjunto personalizado com nome e cores à escolha.',
    image: 'https://images.pexels.com/photos/7180295/pexels-photo-7180295.jpeg',
    category: 'Personalizados',
  },
];

export const recipes: Recipe[] = [
  {
    id: '1',
    name: 'Sr. Esquilo',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/8489654/pexels-photo-8489654.jpeg',
    price: 33.50,
    isPaid: true,
    link: 'https://www.mercadopago.com.br/checkout/v1/payment/redirect/7637ff19-dde2-449a-a617-31f17be2612f/payment-option-form-v2/?source=link&preference-id=150955773-97180d94-e20a-44f9-ac58-07c3507c2fb7&router-request-id=3e2bd385-0791-4796-98f7-0f4b7716bd11&p=d02b4a07a5ddc6512bcb212163166d70',
  },
  {
    id: '2',
    name: 'Bolsa Margarida',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/8489728/pexels-photo-8489728.jpeg',
    price: 30.50,
    isPaid: true,
    link: 'https://www.mercadopago.com.br/checkout/v1/payment/redirect/6ceb6914-8194-41f4-8678-c8689daa6609/payment-option-form-v2/?source=link&preference-id=150955773-57561842-3c26-4f39-9425-e3c662e61661&router-request-id=e7d4c04e-0749-443b-91ae-e293c91cef02&p=d02b4a07a5ddc6512bcb212163166d70',
  },
  {
    id: '3',
    name: 'Abelha Beelinda',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/8489723/pexels-photo-8489723.jpeg',
    price: 33.50,
    isPaid: true,
    link: 'https://www.mercadopago.com.br/checkout/v1/payment/redirect/0b7f0bec-9444-48fc-b194-99aa7f4d4405/payment-option-form-v2/?source=link&preference-id=150955773-9e3e880c-c079-4ec6-9b88-c8484ca92d09&router-request-id=e79de84c-725f-443b-83a9-0e2e95ae14d2&p=d02b4a07a5ddc6512bcb212163166d70',
  },
  {
    id: '4',
    name: 'Mini noz',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/8489729/pexels-photo-8489729.jpeg',
    isPaid: true,
    link: 'https://www.instagram.com/p/C92j3N2J12Y/?img_index=1',
  },
  {
    id: '5',
    name: 'Marcador de páginas',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/8489630/pexels-photo-8489630.jpeg',
    isPaid: true,
    link: 'https://www.instagram.com/p/DBFCFnaxORC/?img_index=1',
  },
  {
    id: '6',
    name: 'Mini abelha',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/7354432/pexels-photo-7354432.jpeg',
    isPaid: false,
    link: 'https://www.instagram.com/p/DAdmZWBxLGq/?img_index=1',
  },
  {
    id: '7',
    name: 'Mini margarida',
    description: 'Receita (PDF)',
    image: 'https://images.pexels.com/photos/7354451/pexels-photo-7354451.jpeg',
    isPaid: false,
    link: 'https://www.instagram.com/p/DAjxiJjx3ak/',
  }
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Jessica Fernandes',
    text: 'Pri, estou encantada com suas receitas. Achei muito fácil de crochetar com as fotos lindas do processo.',
    image: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg',
  },
  {
    id: '2',
    name: 'Amanda S. Sousa',
    text: 'Apaixonada pela receita da abelhinha Pri, é uma delicia de crochetar.',
    image: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg',
  },
  {
    id: '3',
    name: 'Bianca Monta',
    text: 'Adorei sua receita, estava procurando uma dessa a tempos, procurei até em receitas americanas e não encontrava. Obrigada',
    image: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg',
  },
];